### ISSUE TITLE
pass token back to dgraph

### ISSUE THREAD

**Issue by iluminae** [Schartey/dgraph-lambda-go#11]
There is a provided graphql client, but it does not have the authorization token applied to it to pass back to the server - Is there a process for this I am missing?

I basically had to ignore it by setting a new client:
```go
type transport resolver.AuthHeader
func (t transport) RoundTrip(req *http.Request) (*http.Response, error) {
        req.Header.Add(t.Key, t.Value)
        return http.DefaultTransport.RoundTrip(req)
}

func main() {
  api.RunServer(func(r *resolver.Resolver, gql *graphql.Client, dql *dgo.Dgraph) {
    r.ResolveFunc("Query.mylambda",
      func(ctx context.Context, input, _ []byte, ah resolver.AuthHeader) (interface{}, error) {
        gql = graphql.NewClient(dgraphURL+"/graphql", &http.Client{Transport: transport(ah)})
        return mylambda(ctx, input, gql)
      },
    )
  })
}
```

I _think_ its less of a deal for the dql client since that is gRPC and you can probably toss metadata into the context and have it be transferred as headers. (though I did not test this since I do not need it atm)

**Comment by Schartey** [comment]
Hi, I'm sorry for the late response.
I was not able to work too much on the project, but now I'm developing again.
A lot has changed since you provided this feedback. As of now the project is able to generate resolvers by itself.

In terms of your feedback, there is now no default dql client provided anymore. You can now inject your own client as you can see here [Inject custom dependencies](https://github.com/Schartey/dgraph-lambda-go#inject-custom-dependencies)

I hope the response is not too late for you. Thank you.
